# Generated by Django 4.1.1 on 2022-10-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Displayed name of tag', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of art', max_length=50)),
                ('img_url', models.CharField(help_text='URL for art file', max_length=200)),
                ('description', models.CharField(help_text='Supplementary description of art', max_length=280)),
                ('date_created', models.DateField(help_text='Date art was created/last saved')),
                ('img_tag', models.ManyToManyField(help_text='Select tags to apply to this art', to='gallery.tag')),
            ],
        ),
    ]
