# Generated by Django 4.1.1 on 2022-10-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='production_ready',
            field=models.BooleanField(default=True, help_text='Is this image ready for deploy?'),
            preserve_default=False,
        ),
    ]
