# Generated by Django 4.1.1 on 2022-10-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Display name for category page', max_length=25)),
                ('description', models.TextField(help_text='Content of category page')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Display name for link', max_length=25)),
                ('link_url', models.CharField(help_text='Full URL for link', max_length=50)),
                ('description', models.CharField(help_text='Description to accompany link', max_length=50)),
                ('link_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpages.category')),
            ],
        ),
    ]
