# Generated by Django 4.1.1 on 2022-10-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(help_text='Description to accompany link', max_length=280),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_url',
            field=models.CharField(help_text='Full URL for link', max_length=100),
        ),
    ]
